- op: replace
  path: /spec/template/spec/containers/0/image
  value: cypstrate:latest
- op: replace
  path: /spec/template/spec/containers/0/args
  value:
    [
      "cypstrate.CypstrateModel",
      "--broker-url",
      "kafka-cluster-kafka-bootstrap.local:9092",
      "--data-dir",
      "/data",
    ]
- op: remove
  path: /spec/template/spec/imagePullSecrets
