apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-scout
spec:
  template:
    spec:
      containers:
        - name: np-scout
          image: np-scout:latest
          args:
            [
              "np_scout.NPScoutModel",
              "--broker-url",
              "kafka-cluster-kafka-bootstrap.local:9092",
              "--data-dir",
              "/data",
            ]
      imagePullSecrets:
