apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-scout
spec:
  template:
    spec:
      containers:
        - name: np-scout
          image: np-scout:latest
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.local:9092
      imagePullSecrets:
