apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nerdd-frontend-certificate
spec:
  secretName: domain-tls-staging
  dnsNames:
    - "dev-nerdd.univie.ac.at"
  issuerRef:
    name: acme-issuer-staging
    namespace: cert-manager
    kind: Issuer