apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme-issuer-staging
spec:
  acme:
    # Production server is on https://acme-v02.api.letsencrypt.org/directory
    # Use staging by default.
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-secret-staging
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik