load('../../common.Tiltfile', 'kustomize_resource')

kustomize_resource(
    workload='message-broker',
    kustomization_path='./envs/local/',
    namespace='local-kafka',
    create_namespace=True,
    resource_deps=['strimzi', 'external-secrets-check'],
    labels=["infra"]
)