load('../../common.Tiltfile', 'kustomize_resource')

kustomize_resource(
    workload='message-broker',
    kustomization_path='./envs/local/',
    resource_deps=['strimzi', 'external-secrets-check'],
    labels=["infra"]
)