load('../../common.Tiltfile', 'kustomize_resource', 'build_nerdd_module')

project_name = 'skin-doctor-ternary'
repository_name = 'skin-doctor'
repository_url = 'https://github.com/molinfo-vienna/{}'.format(repository_name)

build_nerdd_module(
    project_name,
    repository_url,
    repository_name=repository_name,
    dockerfile_path='Dockerfile.{}'.format(project_name),
    live_update_module_and_link=False,
)

# deploy to kubernetes
kustomize_resource(
    workload=project_name,
    kustomization_path='./envs/local/',
    namespace='local',
    resource_deps=['message-broker', 'keda', 'storage'],
    labels=['modules']
)
