kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: microk8s-hostpath