load('../../common.Tiltfile', 'kustomize_resource')

kustomize_resource(
    workload='redpanda-console',
    kustomization_path='./envs/local/',
    namespace='redpanda',
    create_namespace=True,
    resource_deps=['message-broker', 'nginx-gateway'],
    labels=['infra']
)
