load('../../common.Tiltfile', 'kustomize_resource')

kustomize_resource(
    workload='redpanda-console',
    kustomization_path='./envs/local/',
    namespace='redpanda',
    create_namespace=True,
    resource_deps=['kafka', 'traefik'],
    labels=['infra']
)