load('../../common.Tiltfile', 'kustomize_resource')

kustomize_resource(
    workload='redpanda-console',
    kustomization_path='./envs/local/',
    namespace='local',
    resource_deps=['kafka', 'haproxy-kubernetes-ingress'],
    labels=['infra']
)