apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyplebrity
spec:
  template:
    spec:
      containers:
        - name: cyplebrity
          image: cyplebrity:latest
          args:
            [
              "cyplebrity.CyplebrityModel",
              "--broker-url",
              "kafka-cluster-kafka-bootstrap.local:9092",
              "--data-dir",
              "/data",
            ]
      imagePullSecrets:
