apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: APP_NAME-broker-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: broker-store
  target:
    name: APP_NAME-broker-config
  dataFrom:
    - extract:
        key: broker-config
