apiVersion: batch/v1
kind: Job
metadata:
  name: nerdd-init-system
  labels:
    app: nerdd-init-system
spec:
  template:
    metadata:
      labels:
        app: nerdd-init-system
    spec:
      containers:
        - name: nerdd-init-system
          image: ghcr.io/molinfo-vienna/nerdd-process-jobs:latest
          imagePullPolicy: IfNotPresent
          command: [ "/env/bin/nerdd_init" ]
          args:
            - --channel=$(CHANNEL)
            - --broker-url=$(BROKER_URL)
            - --broker-username=$(BROKER_USERNAME)
            - --broker-password=$(BROKER_PASSWORD)
          env:
            - name: CHANNEL
              valueFrom:
                secretKeyRef:
                  name: broker-config-init-system
                  key: channel
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: broker-config-init-system
                  key: broker_url
            - name: BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: broker-config-init-system
                  key: broker_username
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-config-init-system
                  key: broker_password
          volumeMounts:
            - name: data
              mountPath: "/data"

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
      restartPolicy: Never
  backoffLimit: 4
