apiVersion: batch/v1
kind: Job
metadata:
  name: nerdd-init-system
spec:
  template:
    spec:
      containers:
        - name: nerdd-init-system
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.prod:9092