apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
# resources:
#   - ../../base

# patches:
#   - target:
#       kind: Job
#       name: nerdd-init-system-job
#     path: patch-job.yaml
