apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ui
rules:
  - apiGroups:
    - argoproj.io
    resources:
    - workflows
    - workflows/finalizers
    - workfloweventbindings
    - workfloweventbindings/finalizers
    - workflowtemplates
    - workflowtemplates/finalizers
    - cronworkflows
    - cronworkflows/finalizers
    - clusterworkflowtemplates
    - clusterworkflowtemplates/finalizers
    - workflowtasksets
    - workflowtasksets/finalizers
    - workflowtaskresults
    - workflowtaskresults/finalizers
    - workflowartifactgctasks
    - workflowartifactgctasks/finalizers
    verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ui:ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ui
subjects:
- kind: ServiceAccount
  name: ui
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-cluster-template
rules:
- apiGroups:
  - argoproj.io
  resources:
  - clusterworkflowtemplates
  - clusterworkflowtemplates/finalizers
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ui:ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ui
subjects:
- kind: ServiceAccount
  name: ui
  namespace: argo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui