apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  labels:
    app: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
        - name: redpanda-console
          image: docker.redpanda.com/vectorized/console
          env:
          - name: KAFKA_BROKERS
            value: my-cluster-kafka-bootstrap.kafka:9092
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
spec:
  selector:
    app: redpanda-console
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080