load('ext://git_resource', 'git_checkout')
load('../../common.Tiltfile', 'kustomize_resource')

USE_PRODUCTION_IMAGE = False

# checkout source code
project_name = 'nerdd-frontend'
repository_url = 'https://github.com/molinfo-vienna/{}'.format(project_name)
project_dir = '../../repos/{}'.format(project_name)
if not os.path.exists(project_dir):
    git_checkout(
        repository_url, 
        checkout_dir=project_dir
    )

# choose docker file
if USE_PRODUCTION_IMAGE:
    docker_build(
        project_name,
        context=project_dir,
    )
else:
    docker_build(
        project_name,
        context=project_dir,
        dockerfile='{}/Dockerfile.dev'.format(project_dir) ,
        live_update=[
            sync(project_dir, '/app')
        ],
    )

# deploy to kubernetes
kustomize_resource(
    workload=project_name,
    kustomization_path='./envs/local/',
    namespace='local',
    resource_deps=['nerdd-backend', 'haproxy-kubernetes-ingress'],
    labels=['frontend']
)