apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - broker-config-es.yaml
  - s3-config-es.yaml
  - route.yaml
  - client-settings.yaml

patches:
  - target:
      kind: Deployment
      name: nerdd-backend
    path: patch-deployment.yaml
