apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdd-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nerdd-backend
          image: nerdd-backend:latest
          env:
            - name: DB_HOST
              value: rethinkdb.local
            - name: DB_PORT
              value: "28015"
      affinity: null
