apiVersion: apps/v1
kind: Deployment
metadata:
  name: cypstrate
  labels:
    app: cypstrate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cypstrate
  template:
    metadata:
      labels:
        app: cypstrate
    spec:
      containers:
        - name: cypstrate
          image: cypstrate