apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # nginx gateway fabric
  - https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v2.5.1/deploy/crds.yaml
  - rbac.yaml
  - gateway-class.yaml
  - proxy.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - nginx-gateway-issuer.yaml

  - issuer.yaml
  - gateway.yaml
