apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  labels:
    app.kubernetes.io/instance: nginx-gateway
    app.kubernetes.io/name: nginx-gateway
    app.kubernetes.io/version: 2.5.1
  name: nginx-gateway-proxy-config
spec:
  kubernetes:
    deployment:
      container:
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/nginx/nginx-gateway-fabric/nginx
          tag: 2.5.1
      replicas: 1
    service:
      externalTrafficPolicy: Local
      type: LoadBalancer
