apiVersion: apps/v1
kind: Deployment
metadata:
  name: skin-doctor-cp
spec:
  template:
    spec:
      containers:
        - name: skin-doctor-cp
          args:
            [
              "skin_doctor.SkinDoctorCPModel",
              "--broker-url",
              "kafka-cluster-kafka-bootstrap.dev:9092",
              "--data-dir",
              "/data",
            ]