apiVersion: apps/v1
kind: Deployment
metadata:
  name: skin-doctor-ternary
  labels:
    app: skin-doctor-ternary
spec:
  selector:
    matchLabels:
      app: skin-doctor-ternary
  template:
    metadata:
      labels:
        app: skin-doctor-ternary
    spec:
      containers:
        - name: skin-doctor-ternary
          image: ghcr.io/molinfo-vienna/skin-doctor-ternary:latest
          command: ["/env/bin/nerdd_prediction_server"]
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: "1"
              memory: 10G
            limits:
              cpu: "1"
              memory: 12G
      # important for long-running requests: we give 1h to terminate the current prediction task
      terminationGracePeriodSeconds: 3600
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
