apiVersion: apps/v1
kind: Deployment
metadata:
  name: skin-doctor-ternary
  labels:
    app: skin-doctor-ternary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skin-doctor-ternary
  template:
    metadata:
      labels:
        app: skin-doctor-ternary
    spec:
      containers:
        - name: skin-doctor-ternary
          image: ghcr.io/molinfo-vienna/skin-doctor-ternary:latest
          env:
            - name: KAFKA_BROKER_URL
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 1
              memory: 10G
            limits:
              cpu: 1
              memory: 12G
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
