apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=skin-doctor-ternary
      - modelClass=skin_doctor.SkinDoctorTernaryModel
      - cpuRequest=1
      - memRequest=12G
      - cpuLimit=1
      - memLimit=12G
