apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: skin-doctor-ternary-scaler
  labels:
    deploymentName: skin-doctor-ternary-scaler
spec:
  scaleTargetRef:
    name: skin-doctor-ternary
  pollingInterval: 1
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        topic: skin-doctor-ternary-checkpoints
        offsetResetPolicy: earliest
        bootstrapServers: kafka-cluster-kafka-bootstrap.dev:9092
        consumerGroup: predict-checkpoints-skin-doctor-ternary
        lagThreshold: "5"
        limitToPartitionsWithLag: "true"
