apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdd-process-jobs
  labels:
    app: nerdd-process-jobs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nerdd-process-jobs
  template:
    metadata:
      labels:
        app: nerdd-process-jobs
    spec:
      containers:
        - name: nerdd-process-jobs
          image: ghcr.io/molinfo-vienna/nerdd-process-jobs:latest
          args:
            - --channel=$(CHANNEL)
            - --broker-url=$(BROKER_URL)
            - --broker-username=$(BROKER_USERNAME)
            - --broker-password=$(BROKER_PASSWORD)
            - --data-dir=/data
          env:
            - name: CHANNEL
              valueFrom:
                secretKeyRef:
                  name: broker-config-process-jobs
                  key: channel
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: broker-config-process-jobs
                  key: broker_url
            - name: BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: broker-config-process-jobs
                  key: broker_username
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-config-process-jobs
                  key: broker_password
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: "1"
              memory: 3G
            limits:
              cpu: "1"
              memory: 6G
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
