apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdd-process-jobs
  labels:
    app: nerdd-process-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nerdd-process-jobs
  template:
    metadata:
      labels:
        app: nerdd-process-jobs
    spec:
      containers:
        - name: nerdd-process-jobs
          image: ghcr.io/molinfo-vienna/nerdd-process-jobs:latest
          env:
            - name: KAFKA_BROKER_URL
              value: <to-patch>
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 1
              memory: 3G
            limits:
              cpu: 1
              memory: 6G
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
