apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdd-process-jobs
  labels:
    app: nerdd-process-jobs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nerdd-process-jobs
  template:
    metadata:
      labels:
        app: nerdd-process-jobs
    spec:
      containers:
        - name: nerdd-process-jobs
          image: ghcr.io/molinfo-vienna/nerdd-process-jobs:latest
          args:
            - --channel=$(CHANNEL)
            - --broker-url=$(BROKER_URL)
            - --broker-username=$(BROKER_USERNAME)
            - --broker-password=$(BROKER_PASSWORD)
            - --data-dir=/data
            - --s3-url=$(S3_URL)
            - --s3-bucket=$(S3_BUCKET)
            - --s3-access-key-id=$(S3_ACCESS_KEY_ID)
            - --s3-secret-access-key=$(S3_SECRET_ACCESS_KEY)
          env:
            - name: CHANNEL
              valueFrom:
                secretKeyRef:
                  name: broker-config-process-jobs
                  key: channel
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: broker-config-process-jobs
                  key: broker_url
            - name: BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: broker-config-process-jobs
                  key: broker_username
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-config-process-jobs
                  key: broker_password
            - name: S3_URL
              valueFrom:
                secretKeyRef:
                  name: s3-config-process-jobs
                  key: s3_url
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-config-process-jobs
                  key: s3_bucket
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-config-process-jobs
                  key: s3_access_key_id
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-config-process-jobs
                  key: s3_secret_access_key
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: "1"
              memory: 3G
            limits:
              cpu: "1"
              memory: 6G
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
