load('../../common.Tiltfile', 'kustomize_resource', 'build_nerdd_module')

USE_PRODUCTION_IMAGE = False
project_name = 'cypstrate'
repository_url = 'https://github.com/molinfo-vienna/{}'.format(project_name)

build_nerdd_module(
    project_name,
    repository_url,
    dockerfile_path='Dockerfile' if USE_PRODUCTION_IMAGE else 'Dockerfile.dev',
    live_update_module_and_link=not USE_PRODUCTION_IMAGE,
)

# deploy to kubernetes
kustomize_resource(
    workload=project_name,
    kustomization_path='./envs/local/',
    namespace='local',
    resource_deps=['message-broker', 'keda', 'storage'],
    labels=['modules']
)
