apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=skin-doctor-cp
      - modelClass=skin_doctor.SkinDoctorCPModel
      - cpuRequest=1
      - memRequest=5Gi
      - cpuLimit=1
      - memLimit=5Gi
