apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: skin-doctor-cp-scaler
  labels:
    deploymentName: skin-doctor-cp-scaler
spec:
  scaleTargetRef:
    name: skin-doctor-cp
  pollingInterval: 1
  cooldownPeriod: 30
  minReplicaCount: 3
  maxReplicaCount: 3
  triggers:
    - type: kafka
      metadata:
        topic: skin-doctor-cp-checkpoints
        offsetResetPolicy: earliest
        bootstrapServers: kafka-cluster-kafka-bootstrap.dev:9092
        consumerGroup: predict-checkpoints-skin-doctor-cp
        lagThreshold: "5"
        limitToPartitionsWithLag: "true"
