apiVersion: apps/v1
kind: Deployment
metadata:
  name: gloryx
  labels:
    app: gloryx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gloryx
  template:
    metadata:
      labels:
        app: gloryx
    spec:
      containers:
        - name: gloryx
          image: gloryx