apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-scout
  labels:
    app: np-scout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: np-scout
  template:
    metadata:
      labels:
        app: np-scout
    spec:
      containers:
        - name: np-scout
          image: ghcr.io/molinfo-vienna/np-scout:latest
          env:
            - name: KAFKA_BROKER_URL
              value: <to-patch>
          volumeMounts:
            - name: data
              mountPath: "/data"
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
