apiVersion: apps/v1
kind: Deployment
metadata:
  name: gloryx
  labels:
    app: gloryx
spec:
  selector:
    matchLabels:
      app: gloryx
  template:
    metadata:
      labels:
        app: gloryx
    spec:
      containers:
        - name: gloryx
          image: ghcr.io/molinfo-vienna/gloryx:latest
          command: ["/env/bin/nerdd_prediction_server"]
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 10m
              memory: 1Gi
            limits:
              cpu: "10"
              memory: 7Gi
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
