apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - image=ghcr.io/molinfo-vienna/gloryx:latest
      - appName=gloryx
      - modelClass=gloryx.GloryXModel
      - cpuRequest=4
      - memRequest=8Gi
      - cpuLimit=6
      - memLimit=8Gi
