apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: gloryx-scaler
  labels:
    deploymentName: gloryx-scaler
spec:
  scaleTargetRef:
    name: gloryx
  pollingInterval: 1
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 10
  limitToPartitionsWithLag: true
  triggers:
    - type: kafka
      metadata:
        topic: gloryx-checkpoints
        offsetResetPolicy: earliest
        bootstrapServers: kafka-cluster-kafka-bootstrap.dev:9092
        consumerGroup: predict-checkpoints-gloryx
        lagThreshold: "5"
