apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: blockpool-kafka
spec:
  failureDomain: host
  replicated:
    size: 2
    minSize: 1
  deviceClass: ssd
  parameters:
    compression_mode: none
