kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem