load('../../common.Tiltfile', 'kustomize_resource')

kustomize_resource(
    workload='s3',
    kustomization_path='./envs/local/',
    namespace='local-s3',
    create_namespace=True,
    port_forwards=['9000:9000', '9090:9090'],
    resource_deps=['minio-operator', 'external-secrets-check'],
    labels=['infra']
)
