apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    replicas: 3
    version: 3.8.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: false
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    storage:
      size: 300Gi
      type: persistent-claim
      class: rook-cephfs
      deleteClaim: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      producer.max.request.size: 10485760
      consumer.max.request.size: 10485760
      max.partition.fetch.bytes: 10485760
      message.max.bytes: 10485760
      inter.broker.protocol.version: "3.8"
  zookeeper:
    replicas: 3
    storage:
      size: 300Gi
      type: persistent-claim
      class: rook-cephfs
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}