apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: serialization-requests
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    cleanup.policy: compact
