load('ext://git_resource', 'git_checkout')
load('../../common.Tiltfile', 'kustomize_resource', 'extract_entrypoint')
load('ext://restart_process', 'custom_build_with_restart')

USE_PRODUCTION_IMAGE = True

# checkout source code
project_name = 'awesom'
repository_url = 'https://github.com/molinfo-vienna/aweSOM-image'
project_dir = '../../repos/aweSOM-image'
if not os.path.exists(project_dir):
    git_checkout(
        repository_url, 
        checkout_dir=project_dir
    )

docker_build(
    project_name,
    context=project_dir,
)


# deploy to kubernetes
kustomize_resource(
    workload=project_name,
    kustomization_path='./envs/local/',
    namespace='local',
    resource_deps=['message-broker', 'keda', 'storage'],
    labels=['modules']
)