apiVersion: apps/v1
kind: Deployment
metadata:
  name: fame3r
spec:
  template:
    spec:
      containers:
        - name: fame3r
          image: fame3r:latest
          args:
            [
              "fame3r.fame3r_model.Fame3RModel",
              "--broker-url",
              "kafka-cluster-kafka-bootstrap.local:9092",
              "--data-dir",
              "/data",
            ]
      imagePullSecrets:
