apiVersion: apps/v1
kind: Deployment
metadata:
  name: fame3r
spec:
  template:
    spec:
      containers:
        - name: fame3r
          image: fame3r:latest
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.local:9092
