- op: replace
  path: /spec/template/spec/containers/0/image
  value: fame3r:latest
- op: replace
  path: /spec/template/spec/containers/0/args
  value:
    [
      "fame3r.fame3r_model.Fame3RModel",
      "--broker-url",
      "kafka-cluster-kafka-bootstrap.local:9092",
      "--data-dir",
      "/data",
    ]
- op: remove
  path: /spec/template/spec/imagePullSecrets
