apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdd-process-jobs
spec:
  template:
    spec:
      containers:
        - name: nerdd-process-jobs
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.dev:9092
          