apiVersion: apps/v1
kind: Deployment
metadata:
  name: skin-doctor-ternary
spec:
  template:
    spec:
      containers:
        - name: skin-doctor-ternary
          image: skin-doctor-ternary:latest
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.local:9092
