load('../../common.Tiltfile', 'kustomize_resource', 'build_nerdd_image')

project_name = 'trialblazer'
repository_url = 'https://github.com/molinfo-vienna/{}'.format(project_name)

build_nerdd_image(
    project_name,
    repository_url,
    live_update=False,
    live_update_module_and_link=False,
)

# deploy to kubernetes
kustomize_resource(
    workload=project_name,
    kustomization_path='./envs/local/',
    namespace='local',
    resource_deps=['message-broker', 'keda', 'storage'],
    labels=['modules']
)
