apiVersion: apps/v1
kind: Deployment
metadata:
  name: hitdexter
  labels:
    app: hitdexter
spec:
  selector:
    matchLabels:
      app: hitdexter
  template:
    metadata:
      labels:
        app: hitdexter
    spec:
      containers:
        - name: hitdexter
          image: ghcr.io/molinfo-vienna/hitdexter:latest
          command: ["/env/bin/nerdd_prediction_server"]
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 10m
              memory: 600Mi
            limits:
              cpu: 4000m
              memory: 2G
      # important for long-running requests: we give 1h to terminate the current prediction task
      terminationGracePeriodSeconds: 3600
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
