apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - image=ghcr.io/molinfo-vienna/hitdexter:latest
      - appName=hitdexter3
      - modelClass=hitdexter.HitDexter3Model
      - cpuRequest=4000m
      - memRequest=2G
      - cpuLimit=4000m
      - memLimit=2G
