apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdd-backend
  labels:
    app: nerdd-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nerdd-backend
  template:
    metadata:
      labels:
        app: nerdd-backend
    spec:
      containers:
        - name: nerdd-backend
          image: ghcr.io/molinfo-vienna/nerdd-backend:latest
          imagePullPolicy: Always
          args:
            - --config-name
            - production
            - ++db.host=$(DB_HOST)
            - ++db.port=$(DB_PORT)
            - ++channel.name=$(CHANNEL)
            - ++channel.broker_url=$(BROKER_URL)
            - ++channel.broker_username=$(BROKER_USERNAME)
            - ++channel.broker_password=$(BROKER_PASSWORD)
          env:
            - name: DB_HOST
              value: ""
            - name: DB_PORT
              value: ""
            - name: CHANNEL
              valueFrom:
                secretKeyRef:
                  name: broker-config-backend
                  key: channel
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: broker-config-backend
                  key: broker_url
            - name: BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: broker-config-backend
                  key: broker_username
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-config-backend
                  key: broker_password
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
      # put this container on same host as the database if possible
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: rethinkdb
                topologyKey: kubernetes.io/hostname
        # distribute instances across nodes
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nerdd-backend
              topologyKey: "kubernetes.io/hostname"
