# Sets the maximum request body to 500MB
# There are two places where limits are applied:
# 1) In the nginx config of nerdd-frontend (client_max_body_size directive)
# 2) In this traefik middleware (maxRequestBodyBytes directive)
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: request-size-limit
spec:
  buffering:
    maxRequestBodyBytes: 524288000 # 500MB
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nerdd-backend-ingressroute
  labels:
    app: nerdd-backend
spec:
  entryPoints:
    - websecure
  routes:
    # The trailing slashes at the end of prefixes are important: traefik should not forward
    # URLs like /api-docs to the backend service
    - match: Host(`nerdd.univie.ac.at`) && (PathPrefix(`/api/`) || PathPrefix(`/websocket/`))
      kind: Rule
      services:
        - name: nerdd-backend
          port: 8000
          # Sticky sessions: traefik will set a cookie to ensure that requests from the same client
          # are always routed to the same backend pod. Note that these cookies are purely functional
          # and do not contain any user information (-> no cookie banner needed).
          sticky:
            cookie:
              name: nerdd-lb
              secure: true
              httpOnly: true
      middlewares:
        - name: request-size-limit
    # Note: we do not (and should not) use a middleware to strip the prefixes /api/ or /websocket/,
    # because nerdd-backend / fastapi expects URLs to have these prefixes. However, traefik does
    # forward important headers like X-FORWARDED-FOR, etc. to enable route rewriting in fastapi.
