apiVersion: apps/v1
kind: Deployment
metadata:
  name: skin-doctor-cp
spec:
  template:
    spec:
      containers:
        - name: skin-doctor-cp
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.dev:9092