apiVersion: apps/v1
kind: Deployment
metadata:
  name: glory
spec:
  template:
    spec:
      containers:
        - name: glory
          image: glory:latest
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.local:9092
      imagePullSecrets:
