apiVersion: apps/v1
kind: Deployment
metadata:
  name: glory
spec:
  template:
    spec:
      containers:
        - name: glory
          image: glory:latest
          args:
            [
              "glory.GloryModel",
              "--broker-url",
              "kafka-cluster-kafka-bootstrap.local:9092",
              "--data-dir",
              "/data",
            ]
      imagePullSecrets:
