load('../../common.Tiltfile', 'kustomize_resource')

kustomize_resource(
    workload='traefik',
    kustomization_path='./envs/local/',
    namespace='traefik',
    create_namespace=True,
    port_forwards=['8443:8443', '8000:8000'],
    # We have to wait for the external-secrets webhook to be available before applying the Traefik 
    # configuration. Otherwise, traefik fails with the error message:
    #   Build Failed: Internal error occurred: failed calling webhook 
    #   "validate.externalsecret.external-secrets.io": failed to call webhook: ...connection refused
    resource_deps=['release-name-external-secrets-webhook'],
    labels=['infra']
)