load('../../common.Tiltfile', 'kustomize_resource')
load('ext://restart_process', 'custom_build_with_restart')

USE_PRODUCTION_IMAGE = False

project_name = 'nerdd-serialize-jobs'
project_dir = '../../repos/nerdd-link'

if USE_PRODUCTION_IMAGE:
    docker_build(
        project_name,
        context=project_dir,
        dockerfile='{}/Dockerfile.{}'.format(project_dir, project_name),
    )
else:
    command = "docker buildx build -f {} -t $EXPECTED_REF --build-context repos={} .".format(
        os.path.join(project_dir, 'Dockerfile.{}.dev'.format(project_name)),
        # note: path is relative to context of Dockerfile, e.g. project_dir='../../repos/cypstrate'
        #       -> repos directory is the parent directory of project_dir
        os.path.join(project_dir, '..'),
    )
    custom_build_with_restart(
        project_name,
        command=command,
        deps=[project_dir, "."],
        dir=project_dir,
        live_update=[
            sync(project_dir, "/app"),
        ],
        entrypoint="micromamba run -n nerdd_serialize_jobs nerdd_serialization_server --broker-url $KAFKA_BROKER_URL --data-dir /data"
    )

kustomize_resource(
    project_name,
    kustomization_path='./envs/local',
    namespace='local',
    resource_deps=['kafka', 'keda', 'storage'],
    labels=["services"],
)