apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  # set server.insecure to true, because tls is applied in traefik
  server.insecure: "true"
  server.basehref: "/argocd"
  server.rootpath: "/argocd"
