apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingressroute-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dev-nerdd.univie.ac.at`) && PathPrefix(`/argocd`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
  tls:
    certResolver: default