apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingressroute-https
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dev-nerdd.univie.ac.at`) && PathPrefix(`/argocd`)
      services:
        - name: argocd-server
          port: 80
      middlewares:
        - name: strip-argocd-prefix
    - kind: Rule
      match: Host(`dev-nerdd.univie.ac.at`) && PathPrefix(`/argocd`) && Header(`Content-Type`, `application/grpc`)
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
      middlewares:
        - name: strip-argocd-prefix
  tls:
    certResolver: default
---
# Middleware to strip /argocd prefix
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-argocd-prefix
spec:
  stripPrefix:
    prefixes:
      - /argocd