apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingressroute-https
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dev-nerdd.univie.ac.at`) && PathPrefix(`/argocd`)
      priority: 100
      services:
        - name: argocd-server
          port: 80
      middlewares:
        - name: argocd-strip-prefix
    - kind: Rule
      match: Host(`dev-nerdd.univie.ac.at`) && PathPrefix(`/argocd`) && Header(`Content-Type`, `application/grpc`)
      priority: 101
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
      middlewares:
        - name: argocd-strip-prefix
  tls:
    certResolver: default
