apiVersion: apps/v1
kind: Deployment
metadata:
  name: hitdexter
spec:
  template:
    spec:
      containers:
        - name: hitdexter
          args:
            [
              "hitdexter.HitDexter3Model",
              "--broker-url",
              "kafka-cluster-kafka-bootstrap.dev:9092",
              "--data-dir",
              "/data",
            ]
