load('../../common.Tiltfile', 'kustomize_resource', 'build_nerdd_image')

USE_PRODUCTION_IMAGE = False
project_name = 'nerdd-process-jobs'
repository_name = 'nerdd-link'
repository_url = 'https://github.com/molinfo-vienna/{}'.format(repository_name)

build_nerdd_image(
    project_name,
    repository_url,
    repository_name=repository_name,
    dockerfile_path=(
        'Dockerfile.{}'.format(project_name)
        if USE_PRODUCTION_IMAGE
        else 'Dockerfile.{}.dev'.format(project_name)
    ),
    live_update=not USE_PRODUCTION_IMAGE,
    live_update_module_and_link=False,
)

kustomize_resource(
    project_name,
    kustomization_path='./envs/local',
    namespace='local',
    resource_deps=['message-broker', 'keda', 'storage'],
    labels=["services"],
)
