apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdd-serialize-jobs
spec:
  template:
    spec:
      containers:
        - name: nerdd-serialize-jobs
          args:
            - --channel=$(CHANNEL)
            - --broker-url=$(BROKER_URL)
            - --broker-username=$(BROKER_USERNAME)
            - --broker-password=$(BROKER_PASSWORD)
            - --data-dir=/data
            - --s3-url=$(S3_URL)
            - --s3-bucket=$(S3_BUCKET)
            - --s3-access-key-id=$(S3_ACCESS_KEY_ID)
            - --s3-secret-access-key=$(S3_SECRET_ACCESS_KEY)
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
