apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-config-serialize-jobs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: s3-store
  target:
    name: s3-config-serialize-jobs
    template:
      type: Opaque
      data:
        s3_url: "{{ .s3_url }}"
        s3_bucket: "{{ .s3_bucket }}"
        s3_access_key_id: "{{ .s3_access_key_id }}"
        s3_secret_access_key: "{{ .s3_secret_access_key }}"
  data:
    - secretKey: s3_url
      remoteRef:
        key: s3-config
        property: s3_url
    - secretKey: s3_bucket
      remoteRef:
        key: s3-config
        property: s3_bucket_name
    - secretKey: s3_access_key_id
      remoteRef:
        key: s3-config
        property: s3_access_key_id
    - secretKey: s3_secret_access_key
      remoteRef:
        key: s3-config
        property: s3_secret_access_key
