apiVersion: apps/v1
kind: Deployment
metadata:
  name: skin-doctor-cp
  labels:
    app: skin-doctor-cp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skin-doctor-cp
  template:
    metadata:
      labels:
        app: skin-doctor-cp
    spec:
      containers:
        - name: skin-doctor-cp
          image: ghcr.io/shirte/skin-doctor-cp:latest
          env:
            - name: KAFKA_BROKER_URL
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 1
              memory: 8G
            limits:
              cpu: 1
              memory: 10G
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media