apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../../base

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - minReplicaCount=1
      - maxReplicaCount=10

patches:
  - target:
      kind: KafkaTopic
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: dev-kafka
  # for now, we add s3 args only for modules that use the most recent version of nerdd-link
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --s3-url=$(S3_URL)
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --s3-bucket=$(S3_BUCKET)
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --s3-access-key-id=$(S3_ACCESS_KEY_ID)
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --s3-secret-access-key=$(S3_SECRET_ACCESS_KEY)
