apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ui
  namespace: argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ui
subjects:
- kind: ServiceAccount
  name: ui
  namespace: argo-workflows