apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdd-backend
spec:
  template:
    spec:
      containers:
        - name: nerdd-backend
          env:
            - name: DB_HOST
              value: rethinkdb.dev
            - name: DB_PORT
              value: "28015"
