apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ClusterSecretStore
      name: broker-store
    path: patch-store.yaml
  - target:
      kind: RabbitmqCluster
      name: rabbitmq
    path: patch-rabbitmq.yaml
