apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - broker-store.yaml
  - rabbitmq-config.yaml

patches:
  - target:
      kind: RabbitmqCluster
      name: rabbitmq
    path: patch-rabbitmq.yaml
