apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch-kafka.yaml

patches:
  - path: patch-topics.yaml
    target:
      group: kafka.strimzi.io
      version: v1beta2
      kind: KafkaTopic
