apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Kafka
      name: kafka-cluster
    path: patch-kafka.yaml
  - target:
      kind: KafkaNodePool
      name: controller
    path: patch-nodepool.yaml
