apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-certificate
spec:
  secretName: registry-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames: 
  - registry-service.registry.svc.cluster.local