apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: rook-ceph-block