apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fame3r-scaler
  labels:
    deploymentName: fame3r-scaler
spec:
  scaleTargetRef:
    name: fame3r
  pollingInterval: 1
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        topic: fame3r-checkpoints
        offsetResetPolicy: earliest
        bootstrapServers: kafka-cluster-kafka-bootstrap.dev:9092
        consumerGroup: predict-checkpoints-fame3r
        lagThreshold: "5"
