apiVersion: apps/v1
kind: Deployment
metadata:
  name: cypstrate
spec:
  template:
    spec:
      containers:
        - name: cypstrate
          args:
            [
              "cypstrate.CypstrateModel",
              "--broker-url",
              "kafka-cluster-kafka-bootstrap.dev:9092",
              "--data-dir",
              "/data",
            ]
