load('../../common.Tiltfile', 'kustomize_resource', 'build_nerdd_image')

USE_PRODUCTION_IMAGE = False
project_name = 'nerdd-init-system'
repository_name = 'nerdd-link'
repository_url = 'https://github.com/molinfo-vienna/{}'.format(repository_name)
dockerfile_project_name = 'nerdd-process-jobs'

build_nerdd_image(
    project_name,
    repository_url,
    repository_name=repository_name,
    dockerfile_path=(
        'Dockerfile.{}'.format(dockerfile_project_name)
        if USE_PRODUCTION_IMAGE
        else 'Dockerfile.{}.dev'.format(dockerfile_project_name)
    ),
    live_update=not USE_PRODUCTION_IMAGE,
    live_update_module_and_link=False,
)

# deploy to kubernetes
kustomize_resource(
    workload=project_name,
    kustomization_path='./envs/local/',
    namespace='local',
    resource_deps=['message-broker', 'keda-operator', 'storage'],
    labels=['services']
)
