apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-scout
spec:
  template:
    spec:
      containers:
        - name: np-scout
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.dev:9092