apiVersion: apps/v1
kind: Deployment
metadata:
  name: gloryx
spec:
  template:
    spec:
      containers:
        - name: gloryx
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.dev:9092