apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
  namespace: monitoring
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC

    [server]
    root_url = %(protocol)s://%(domain)s/grafana/
    serve_from_sub_path = true
