apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC
    
    [server]
    domain: dev-nerdd.univie.ac.at
    root_url: https://dev-nerdd.univie.ac.at/grafana/
    serve_from_sub_path: true