apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dev-nerdd.univie.ac.at`) && PathPrefix(`/prometheus`)
      kind: Rule
      services:
        - name: prometheus-k8s
          port: 9090
      middlewares:
        - name: prometheus-strip-prefix
  tls:
    certResolver: default
