apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingressroute.yaml
- kube-prometheus-0.14.0/prometheusAdapter-serviceMonitor.yaml
- kube-prometheus-0.14.0/prometheus-serviceAccount.yaml
- kube-prometheus-0.14.0/blackboxExporter-configuration.yaml
- kube-prometheus-0.14.0/prometheusAdapter-clusterRoleBinding.yaml
- kube-prometheus-0.14.0/prometheus-prometheus.yaml
- kube-prometheus-0.14.0/nodeExporter-clusterRole.yaml
- kube-prometheus-0.14.0/prometheusAdapter-clusterRoleAggregatedMetricsReader.yaml
- kube-prometheus-0.14.0/nodeExporter-networkPolicy.yaml
- kube-prometheus-0.14.0/nodeExporter-daemonset.yaml
- kube-prometheus-0.14.0/kubernetesControlPlane-prometheusRule.yaml
- kube-prometheus-0.14.0/prometheusAdapter-clusterRole.yaml
- kube-prometheus-0.14.0/kubernetesControlPlane-serviceMonitorKubeScheduler.yaml
- kube-prometheus-0.14.0/prometheusOperator-deployment.yaml
- kube-prometheus-0.14.0/prometheusAdapter-serviceAccount.yaml
- kube-prometheus-0.14.0/kubeStateMetrics-clusterRole.yaml
- kube-prometheus-0.14.0/kubeStateMetrics-prometheusRule.yaml
- kube-prometheus-0.14.0/prometheusOperator-service.yaml
- kube-prometheus-0.14.0/kubeStateMetrics-networkPolicy.yaml
- kube-prometheus-0.14.0/grafana-config.yaml
- kube-prometheus-0.14.0/kubernetesControlPlane-serviceMonitorKubeControllerManager.yaml
- kube-prometheus-0.14.0/prometheusAdapter-clusterRoleServerResources.yaml
- kube-prometheus-0.14.0/prometheus-networkPolicy.yaml
- kube-prometheus-0.14.0/nodeExporter-serviceAccount.yaml
- kube-prometheus-0.14.0/grafana-serviceAccount.yaml
- kube-prometheus-0.14.0/grafana-serviceMonitor.yaml
- kube-prometheus-0.14.0/alertmanager-alertmanager.yaml
- kube-prometheus-0.14.0/prometheus-roleConfig.yaml
- kube-prometheus-0.14.0/nodeExporter-serviceMonitor.yaml
- kube-prometheus-0.14.0/blackboxExporter-clusterRole.yaml
- kube-prometheus-0.14.0/prometheus-podDisruptionBudget.yaml
- kube-prometheus-0.14.0/kubeStateMetrics-serviceAccount.yaml
- kube-prometheus-0.14.0/kubeStateMetrics-serviceMonitor.yaml
- kube-prometheus-0.14.0/grafana-dashboardDefinitions.yaml
- kube-prometheus-0.14.0/alertmanager-podDisruptionBudget.yaml
- kube-prometheus-0.14.0/grafana-dashboardDatasources.yaml
- kube-prometheus-0.14.0/blackboxExporter-networkPolicy.yaml
- kube-prometheus-0.14.0/prometheusOperator-clusterRoleBinding.yaml
- kube-prometheus-0.14.0/prometheusAdapter-podDisruptionBudget.yaml
- kube-prometheus-0.14.0/prometheus-clusterRole.yaml
- kube-prometheus-0.14.0/alertmanager-serviceMonitor.yaml
- kube-prometheus-0.14.0/grafana-dashboardSources.yaml
- kube-prometheus-0.14.0/prometheusOperator-prometheusRule.yaml
- kube-prometheus-0.14.0/prometheus-roleSpecificNamespaces.yaml
- kube-prometheus-0.14.0/prometheus-serviceMonitor.yaml
- kube-prometheus-0.14.0/grafana-networkPolicy.yaml
- kube-prometheus-0.14.0/alertmanager-networkPolicy.yaml
- kube-prometheus-0.14.0/kubernetesControlPlane-serviceMonitorCoreDNS.yaml
- kube-prometheus-0.14.0/prometheus-service.yaml
- kube-prometheus-0.14.0/alertmanager-service.yaml
- kube-prometheus-0.14.0/setup/0probeCustomResourceDefinition.yaml
- kube-prometheus-0.14.0/setup/0prometheusagentCustomResourceDefinition.yaml
- kube-prometheus-0.14.0/setup/0servicemonitorCustomResourceDefinition.yaml
- kube-prometheus-0.14.0/setup/0prometheusCustomResourceDefinition.yaml
- kube-prometheus-0.14.0/setup/0podmonitorCustomResourceDefinition.yaml
- kube-prometheus-0.14.0/setup/0thanosrulerCustomResourceDefinition.yaml
- kube-prometheus-0.14.0/setup/namespace.yaml
- kube-prometheus-0.14.0/setup/0scrapeconfigCustomResourceDefinition.yaml
- kube-prometheus-0.14.0/setup/0alertmanagerCustomResourceDefinition.yaml
- kube-prometheus-0.14.0/setup/0prometheusruleCustomResourceDefinition.yaml
- kube-prometheus-0.14.0/setup/0alertmanagerConfigCustomResourceDefinition.yaml
- kube-prometheus-0.14.0/blackboxExporter-deployment.yaml
- kube-prometheus-0.14.0/nodeExporter-clusterRoleBinding.yaml
- kube-prometheus-0.14.0/prometheus-roleBindingSpecificNamespaces.yaml
- kube-prometheus-0.14.0/prometheusAdapter-roleBindingAuthReader.yaml
- kube-prometheus-0.14.0/grafana-prometheusRule.yaml
- kube-prometheus-0.14.0/kubeStateMetrics-deployment.yaml
- kube-prometheus-0.14.0/prometheus-clusterRoleBinding.yaml
- kube-prometheus-0.14.0/nodeExporter-service.yaml
- kube-prometheus-0.14.0/prometheus-roleBindingConfig.yaml
- kube-prometheus-0.14.0/prometheusAdapter-networkPolicy.yaml
- kube-prometheus-0.14.0/prometheusAdapter-service.yaml
- kube-prometheus-0.14.0/prometheus-prometheusRule.yaml
- kube-prometheus-0.14.0/blackboxExporter-service.yaml
- kube-prometheus-0.14.0/grafana-service.yaml
- kube-prometheus-0.14.0/prometheusOperator-networkPolicy.yaml
- kube-prometheus-0.14.0/alertmanager-secret.yaml
- kube-prometheus-0.14.0/kubePrometheus-prometheusRule.yaml
- kube-prometheus-0.14.0/prometheusOperator-serviceMonitor.yaml
- kube-prometheus-0.14.0/prometheusAdapter-configMap.yaml
- kube-prometheus-0.14.0/kubernetesControlPlane-serviceMonitorKubelet.yaml
- kube-prometheus-0.14.0/blackboxExporter-clusterRoleBinding.yaml
- kube-prometheus-0.14.0/alertmanager-serviceAccount.yaml
- kube-prometheus-0.14.0/prometheusAdapter-clusterRoleBindingDelegator.yaml
- kube-prometheus-0.14.0/kubeStateMetrics-service.yaml
- kube-prometheus-0.14.0/grafana-deployment.yaml
- kube-prometheus-0.14.0/kubernetesControlPlane-serviceMonitorApiserver.yaml
- kube-prometheus-0.14.0/blackboxExporter-serviceMonitor.yaml
- kube-prometheus-0.14.0/prometheusAdapter-apiService.yaml
- kube-prometheus-0.14.0/nodeExporter-prometheusRule.yaml
- kube-prometheus-0.14.0/alertmanager-prometheusRule.yaml
- kube-prometheus-0.14.0/kubeStateMetrics-clusterRoleBinding.yaml
- kube-prometheus-0.14.0/prometheusOperator-serviceAccount.yaml
- kube-prometheus-0.14.0/prometheusAdapter-deployment.yaml
- kube-prometheus-0.14.0/blackboxExporter-serviceAccount.yaml
- kube-prometheus-0.14.0/prometheusOperator-clusterRole.yaml

- https://raw.githubusercontent.com/robusta-dev/krr/refs/heads/main/docs/krr-in-cluster/krr-in-cluster-job.yaml

patches:
- grafana-config-patch.yaml