apiVersion: apps/v1
kind: Deployment
metadata:
  name: glory
  labels:
    app: glory
spec:
  selector:
    matchLabels:
      app: glory
  template:
    metadata:
      labels:
        app: glory
    spec:
      containers:
        - name: glory
          image: ghcr.io/molinfo-vienna/glory:latest
          command: ["/env/bin/nerdd_prediction_server"]
          resources:
            requests:
              cpu: "4"
              memory: 4Gi
            limits:
              cpu: "6"
              memory: 7Gi
          volumeMounts:
            - name: data
              mountPath: "/data"
      # important for long-running requests: we give 1h to terminate the current prediction task
      terminationGracePeriodSeconds: 3600
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
