apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: glory-scaler
  labels:
    deploymentName: glory-scaler
spec:
  scaleTargetRef:
    name: glory
  pollingInterval: 1
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        topic: glory-checkpoints
        offsetResetPolicy: earliest
        bootstrapServers: kafka-cluster-kafka-bootstrap.dev:9092
        consumerGroup: predict-checkpoints-glory
        lagThreshold: "5"
        limitToPartitionsWithLag: "true"
