apiVersion: apps/v1
kind: Deployment
metadata:
  name: fame
spec:
  template:
    spec:
      containers:
        - name: fame
          args:
            [
              "fame.Fame3Model",
              "--broker-url",
              "kafka-cluster-kafka-bootstrap.dev:9092",
              "--data-dir",
              "/data",
            ]
