load('../../common.Tiltfile', 'kustomize_resource')

# Sometimes, deleting Strimzi resources fails due to finalizers. Avoid that by removing them. We
# do not need them in local development.
local_resource(
    'remove-strimzi-finalizers',
    cmd='''
    kubectl get kafkatopic -A -o json | kubectl patch -f - --type=merge -p '{"metadata":{"finalizers":null}}'
    kubectl patch crd kafkatopics.kafka.strimzi.io -p '{"metadata":{"finalizers":[]}}' --type=merge || true
    ''',
    labels=['infra'],
)

kustomize_resource(
    workload='strimzi', 
    kustomization_path='./envs/local', 
    namespace='strimzi', 
    create_namespace=True,
    resource_deps=['remove-strimzi-finalizers'], 
    labels=['infra']
)