apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

secretGenerator:
  - name: broker-config-init-system
    literals:
      - channel=kafka
      - broker_url=kafka-cluster-kafka-bootstrap.minimum:9092
      - broker_username=""
      - broker_password=""

