apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metal-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
    repoURL: https://github.com/molinfo-vienna/nerdd.git
    revision: HEAD
    directories:
    - path: apps/*/envs/metal
  template:
    metadata:
      name: '{{index .path.segments 1}}'
    spec:
      # The project the application belongs to.
      project: default
      # Source of the application manifests
      source:
        repoURL: https://github.com/molinfo-vienna/nerdd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}'