apiVersion: apps/v1
kind: Deployment
metadata:
  name: gloryx
spec:
  template:
    spec:
      containers:
        - name: gloryx
          image: gloryx:latest
          args:
            [
              "gloryx.GloryXModel",
              "--broker-url",
              "kafka-cluster-kafka-bootstrap.local:9092",
              "--data-dir",
              "/data",
            ]
      imagePullSecrets:
