apiVersion: apps/v1
kind: Deployment
metadata:
  name: gloryx
spec:
  template:
    spec:
      containers:
        - name: gloryx
          image: gloryx:latest
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.local:9092
      imagePullSecrets:
