apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: gloryx
    path: patch-deployment.yaml
  - target:
      kind: ScaledObject
      name: gloryx-scaler
    path: patch-scaler.yaml
  - target:
      kind: KafkaTopic
      name: gloryx-checkpoints
    path: patch-topic.yaml
