apiVersion: apps/v1
kind: Deployment
metadata:
  name: fame3
  labels:
    app: fame3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fame3
  template:
    metadata:
      labels:
        app: fame3
    spec:
      containers:
        - name: fame3
          image: fame3
          volumeMounts:
            - name: data
              mountPath: "/data"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: media