apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
spec:
  template:
    spec:
      containers:
        - name: redpanda-console
          env:
          - name: KAFKA_BROKERS
            value: kafka-cluster-kafka-bootstrap.dev:9092