apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Role
      name: prometheus-k8s
      namespace: default
    patch: |
      - op: replace
        path: /metadata/namespace
        value: dev
  - target:
      kind: RoleBinding
      name: prometheus-k8s
      namespace: default
    patch: |
      - op: replace
        path: /metadata/namespace
        value: dev
