apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Role
      name: prometheus-k8s
      namespace: default
    path: patch-role.yaml
  - target:
      kind: RoleBinding
      name: prometheus-k8s
      namespace: default
    path: patch-rolebinding.yaml
