apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - https://github.com/external-secrets/external-secrets/releases/download/v0.14.4/external-secrets.yaml
  - auth.yaml
  - cluster-secret-store.yaml

patches:
  - target:
      kind: Deployment
      name: external-secrets-cert-controller
    path: patch-cert-controller.yaml
  - target:
      kind: Deployment
      name: external-secrets-webhook
    path: patch-webhook.yaml
