apiVersion: apps/v1
kind: Deployment
metadata:
  name: trialblazer
  labels:
    app: trialblazer
spec:
  selector:
    matchLabels:
      app: trialblazer
  template:
    metadata:
      labels:
        app: trialblazer
    spec:
      containers:
        - name: trialblazer
          image: ghcr.io/shirte/trialblazer:latest
          command: ["/env/bin/nerdd_prediction_server"]
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: "4"
              memory: 2Gi
            limits:
              cpu: "5"
              memory: 4Gi
          # trialblazer uses sklearn MPLs which use all available cores by default
          # -> limit to 4 cores
          env:
            - name: OMP_NUM_THREADS
              value: "4"
            - name: MKL_NUM_THREADS
              value: "4"
            - name: OPENBLAS_NUM_THREADS
              value: "4"
            - name: NUMEXPR_NUM_THREADS
              value: "4"
      # important for long-running requests: we give 1h to terminate the current prediction task
      terminationGracePeriodSeconds: 3600
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
