apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - image=ghcr.io/molinfo-vienna/trialblazer:latest
      - appName=trialblazer
      - modelClass=trialblazer.Nerdd.TrialblazerModel
      - cpuRequest=4
      - memRequest=6Gi
      - cpuLimit=5
      - memLimit=6Gi
