apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: IngressRoute
      name: traefik-dashboard
    path: patch-ingressroute.yaml
  - target:
      kind: Deployment
      name: traefik
    path: patch-deployment.yaml
  - target:
      kind: Service
      name: traefik
    path: patch-service.yaml
