apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch-service.yaml
  - patch-ingressroute.yaml

patches:
  - path: patch-middleware.yaml
