apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch-service.yaml

patches:
  - target:
      kind: IngressRoute
      name: traefik-dashboard
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: PathPrefix(`/traefik/api`) || PathPrefix(`/traefik/dashboard`)
      - op: remove
        path: /spec/routes/0/middlewares
