apiVersion: apps/v1
kind: Deployment
metadata:
  name: fame
  labels:
    app: fame
spec:
  selector:
    matchLabels:
      app: fame
  template:
    metadata:
      labels:
        app: fame
    spec:
      containers:
        - name: fame
          image: ghcr.io/molinfo-vienna/fame:latest
          command: ["/env/bin/nerdd_prediction_server"]
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: "3"
              memory: 17G
            limits:
              cpu: "5"
              memory: 17G
      # important for long-running requests: we give 1h to terminate the current prediction task
      terminationGracePeriodSeconds: 3600
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
