apiVersion: apps/v1
kind: Deployment
metadata:
  name: fame
  labels:
    app: fame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fame
  template:
    metadata:
      labels:
        app: fame
    spec:
      containers:
        - name: fame
          image: ghcr.io/shirte/fame:latest
          env:
            - name: KAFKA_BROKER_URL
              value: <to-patch>
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 4
              memory: 9Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media