apiVersion: apps/v1
kind: Deployment
metadata:
  name: fame
  labels:
    app: fame
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fame
  template:
    metadata:
      labels:
        app: fame
    spec:
      containers:
        - name: fame
          image: ghcr.io/shirte/fame:latest
          env:
            - name: KAFKA_BROKER_URL
              value: <to-patch>
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 4
              memory: 20G
            limits:
              cpu: 4
              memory: 30G
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media