apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=fame3
      - modelClass=fame.Fame3Model
      - cpuRequest=4
      - memRequest=17G
      - cpuLimit=5
      - memLimit=17G
