apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyplebrity
  labels:
    app: cyplebrity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyplebrity
  template:
    metadata:
      labels:
        app: cyplebrity
    spec:
      containers:
        - name: cyplebrity
          image: ghcr.io/molinfo-vienna/cyplebrity:latest
          env:
            - name: KAFKA_BROKER_URL
              value: <to-patch>
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 4000m
              memory: 5Gi
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
