apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyplebrity
  labels:
    app: cyplebrity
spec:
  selector:
    matchLabels:
      app: cyplebrity
  template:
    metadata:
      labels:
        app: cyplebrity
    spec:
      containers:
        - name: cyplebrity
          image: ghcr.io/molinfo-vienna/cyplebrity:latest
          command: ["/env/bin/nerdd_prediction_server"]
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 2000m
              memory: 4Gi
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
