apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cyplebrity-scaler
  labels:
    deploymentName: cyplebrity-scaler
spec:
  scaleTargetRef:
    name: cyplebrity
  pollingInterval: 1
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        topic: cyplebrity-checkpoints
        offsetResetPolicy: earliest
        bootstrapServers: kafka-cluster-kafka-bootstrap.dev:9092
        consumerGroup: predict-checkpoints-cyplebrity
        lagThreshold: "5"
        limitToPartitionsWithLag: "true"
