apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdd-backend
  labels:
    app: nerdd-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nerdd-backend
  template:
    metadata:
      labels:
        app: nerdd-backend
    spec:
      containers:
        - name: nerdd-backend
          image: nerdd-backend
          command: ["/bin/bash", "--login", "-c"]
          args:
            - conda run -n nerdd_backend uvicorn nerdd_backend.main:app
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: '8000'
          volumeMounts:
            - name: data
              mountPath: "/data"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: media
---
apiVersion: v1
kind: Service
metadata:
  name: nerdd-backend
spec:
  selector:
    app: nerdd-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000