apiVersion: batch/v1
kind: Job
metadata:
  name: nerdd-init-system
  labels:
    app: nerdd-init-system
spec:
  template:
    metadata:
      labels:
        app: nerdd-init-system
    spec:
      containers:
        - name: nerdd-init-system
          image: nerdd-init-system
      restartPolicy: Never
  backoffLimit: 4