apiVersion: apps/v1
kind: Deployment
metadata:
  name: cypstrate
  labels:
    app: cypstrate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cypstrate
  template:
    metadata:
      labels:
        app: cypstrate
    spec:
      containers:
        - name: cypstrate
          image: ghcr.io/shirte/cypstrate:latest
          env:
            - name: KAFKA_BROKER_URL
              value: <to-patch>
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 10m
              memory: 1500Mi
            limits:
              cpu: 1500m
              memory: 1500Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media