apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - image=ghcr.io/molinfo-vienna/cypstrate:latest
      - appName=cypstrate
      - modelClass=cypstrate.CypstrateModel
      - cpuRequest=2000m
      - memRequest=5000Mi
      - cpuLimit=3000m
      - memLimit=5000Mi
