apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cypstrate-scaler
  labels:
    deploymentName: cypstrate-scaler
spec:
  scaleTargetRef:
    name: cypstrate
  pollingInterval: 1
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 10
  limitToPartitionsWithLag: true
  triggers:
    - type: kafka
      metadata:
        topic: cypstrate-checkpoints
        offsetResetPolicy: earliest
        bootstrapServers: kafka-cluster-kafka-bootstrap.dev:9092
        consumerGroup: predict-checkpoints-cypstrate
        lagThreshold: "5"
