apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: cypstrate-checkpoints
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 10
  replicas: 1
  config:
    cleanup.policy: compact
