apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: s3-store
spec:
  provider:
    kubernetes:
      remoteNamespace: local
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
      auth:
        serviceAccount:
          name: external-secrets-auth
          namespace: external-secrets
