apiVersion: apps/v1
kind: Deployment
metadata:
  name: fame
spec:
  template:
    spec:
      containers:
        - name: fame
          image: fame:latest
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.local:9092
      imagePullSecrets:
