apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redpanda-console
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nerdd.univie.ac.at`) && PathPrefix(`/redpanda`)
      services:
        - name: redpanda-console
          port: 8080
      middlewares:
        - name: redpanda-strip-prefix-middleware
        - name: redpanda-auth-middleware
  tls:
    certResolver: default
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redpanda-strip-prefix-middleware
spec:
  stripPrefix:
    prefixes:
      - /redpanda
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redpanda-auth-middleware
spec:
  basicAuth:
    secret: redpanda-auth
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redpanda-auth
spec:
  target:
    name: redpanda-auth
    template:
      type: kubernetes.io/basic-auth
      data:
        username: kimberly
        password: "{{ .password}}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: redpanda-auth-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: redpanda-auth-generator
spec:
  length: 25
---

