---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redpanda-auth
spec:
  target:
    name: redpanda-auth
    template:
      type: kubernetes.io/basic-auth
      data:
        username: kimberly
        password: "{{ .password}}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: redpanda-auth-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: redpanda-auth-generator
spec:
  length: 25
