---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redpanda-auth
spec:
  target:
    name: redpanda-auth
    template:
      type: Opaque
      data:
        # store in plain text so we can recover it on server side
        password: "{{ .password }}"
        kimberly: "{{ .password | bcrypt }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: redpanda-auth-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: redpanda-auth-generator
spec:
  length: 25
