apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nerdd-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nerdd@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress: {}
