apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: HTTPRoute
      name: frontend-route
    path: patch-route.yaml
  - target:
      kind: Deployment
      name: nerdd-frontend
    path: patch-deployment.yaml
