apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch-kafka.yaml

patches:
  - target:
      kind: KafkaNodePool
      name: controller
    patch: |
      - op: replace
        path: /spec/storage/class
        value: rook-ceph-block
