apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - broker-store.yaml

patches:
  - target:
      kind: Kafka
      name: kafka-cluster
    path: patch-kafka.yaml
  - target:
      kind: Secret
      name: broker-config
    path: patch-kafka-config.yaml

  - target:
      kind: KafkaNodePool
      name: broker-pool
    path: patch-nodepool2.yaml
