apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    replicas: 3
    # try to put kafka brokers on different machines
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/cluster
                      operator: In
                      values:
                        - kafka-cluster
                    - key: strimzi.io/kind
                      operator: In
                      values:
                        - Kafka
                topologyKey: kubernetes.io/hostname
    storage:
      size: 300Gi
      type: persistent-claim
      class: rook-cephfs
      deleteClaim: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      producer.max.request.size: 10485760
      consumer.max.request.size: 10485760
      max.partition.fetch.bytes: 10485760
      message.max.bytes: 10485760
      inter.broker.protocol.version: "3.8"
  zookeeper:
    replicas: 3
    storage:
      size: 300Gi
      type: persistent-claim
      class: rook-cephfs
      deleteClaim: false
