apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesom
  labels:
    app: awesom
spec:
  selector:
    matchLabels:
      app: awesom
  template:
    metadata:
      labels:
        app: awesom
    spec:
      containers:
        - name: awesom
          image: ghcr.io/molinfo-vienna/awesom:latest
          command: ["/env/bin/nerdd_prediction_server"]
          volumeMounts:
            - name: data
              mountPath: "/data"
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: "4"
              memory: 9Gi
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
