apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app-config
    literals:
      - appName=awesom
      - modelClass=awesom._nerdd.AweSOMModel
      - topic=awesom-checkpoints
      - consumerGroup=predict-checkpoints-awesom
      - cpuRequest=10m
      - memRequest=100Mi
      - cpuLimit=4
      - memLimit=9Gi
