apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: awesom-scaler
  labels:
    deploymentName: awesom-scaler
spec:
  scaleTargetRef:
    name: awesom
  pollingInterval: 1
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        topic: awesom-checkpoints
        offsetResetPolicy: earliest
        bootstrapServers: kafka-cluster-kafka-bootstrap.dev:9092
        consumerGroup: predict-checkpoints-awesom
        lagThreshold: "5"
