apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fame3r-ghcr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ghcr-store
  target:
    name: fame3r-ghcr-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: ghcr-secret
        property: .dockerconfigjson
