- op: replace
  path: /spec/template/spec/containers/0/args
  value:
    [
      "fame3r._nerdd.FAME3RModel",
      "--broker-url",
      "kafka-cluster-kafka-bootstrap.dev:9092",
      "--data-dir",
      "/data",
    ]
